/**
 * 探店数据 - 知名美食博主探访过的店铺
 * 坐标以成都为中心，覆盖火锅、川菜、小吃、面馆、烧烤、甜品等品类
 */
const EXPLORE_DATA = {
  // 博主信息
  bloggers: [
    {
      id: 'b1',
      name: '密子君',
      avatar: '👩‍🍳',
      followers: '1980万',
      platform: '抖音',
      bio: '大胃王美食博主，以惊人食量和真实测评著称',
    },
    {
      id: 'b2',
      name: '盗月社食遇记',
      avatar: '🎬',
      followers: '1260万',
      platform: 'B站',
      bio: '沉浸式美食探店，镜头语言极具感染力',
    },
    {
      id: 'b3',
      name: '唐仁杰',
      avatar: '👨‍🍳',
      followers: '890万',
      platform: '抖音',
      bio: '前米其林厨师，专业级美食测评',
    },
    {
      id: 'b4',
      name: '肉肉大搜索',
      avatar: '🔍',
      followers: '650万',
      platform: 'B站',
      bio: '走街串巷挖掘隐藏小店，接地气测评',
    },
    {
      id: 'b5',
      name: '日食记',
      avatar: '📷',
      followers: '1720万',
      platform: '微博',
      bio: '治愈系美食记录，画面精致如电影',
    },
    {
      id: 'b6',
      name: '吃货请闭眼',
      avatar: '😋',
      followers: '420万',
      platform: 'B站',
      bio: '老北京风味探店，幽默风趣接地气',
    },
  ],

  // 店铺数据
  stores: [
    {
      id: 's001',
      name: '小龙坎老火锅（春熙路概念店）',
      category: '火锅',
      lat: 30.6578,
      lng: 104.0815,
      address: '成都市锦江区春熙路东段1号',
      avgPrice: 120,
      rating: 4.7,
      bloggerId: 'b1',
      bloggerName: '密子君',
      visitDate: '2025-11-15',
      recommendDishes: ['精品毛肚', '九尺鹅肠', '红糖糍粑'],
      tags: ['成都必吃', '排队王', '环境好'],
      note: '密子君一个人吃了8盘肉，毛肚点了4份！',
    },
    {
      id: 's002',
      name: '明婷饭店',
      category: '川菜',
      lat: 30.6712,
      lng: 104.0863,
      address: '成都市金牛区外曹家巷26号',
      avgPrice: 70,
      rating: 4.6,
      bloggerId: 'b2',
      bloggerName: '盗月社食遇记',
      visitDate: '2025-10-20',
      recommendDishes: ['脑花豆腐', '荷叶酱肉', '奇香排骨'],
      tags: ['苍蝇馆子', '成都老字号', '性价比高'],
      note: '盗月社说这是他们在成都吃过最地道的苍蝇馆子',
    },
    {
      id: 's003',
      name: '玉林串串香（总店）',
      category: '火锅',
      lat: 30.6289,
      lng: 104.0542,
      address: '成都市武侯区玉林街26号',
      avgPrice: 65,
      rating: 4.5,
      bloggerId: 'b4',
      bloggerName: '肉肉大搜索',
      visitDate: '2025-09-28',
      recommendDishes: ['牛肉串串', '小郡肝', '冰粉'],
      tags: ['串串鼻祖', '夜宵圣地', '本地人推荐'],
      note: '肉肉说这家是成都串串的活化石，牛肉腌料绝了',
    },
    {
      id: 's004',
      name: '陈麻婆豆腐（骡马市店）',
      category: '川菜',
      lat: 30.6658,
      lng: 104.0713,
      address: '成都市青羊区西玉龙街197号',
      avgPrice: 55,
      rating: 4.4,
      bloggerId: 'b3',
      bloggerName: '唐仁杰',
      visitDate: '2025-10-05',
      recommendDishes: ['麻婆豆腐', '宫保鸡丁', '夫妻肺片'],
      tags: ['百年老店', '正宗川味', '必打卡'],
      note: '唐仁杰评价：教科书级的麻婆豆腐，麻辣鲜香烫酥嫩，六味俱全',
    },
    {
      id: 's005',
      name: '洞子口张老二凉粉',
      category: '小吃',
      lat: 30.6598,
      lng: 104.0782,
      address: '成都市锦江区文殊院街39号',
      avgPrice: 20,
      rating: 4.5,
      bloggerId: 'b1',
      bloggerName: '密子君',
      visitDate: '2025-11-16',
      recommendDishes: ['甜水面', '黄凉粉', '钟水饺'],
      tags: ['文殊院美食', '小吃天堂', '人均20'],
      note: '甜水面让密子君连吃三碗，说面条劲道得弹牙',
    },
    {
      id: 's006',
      name: '五里关火锅（建设路店）',
      category: '火锅',
      lat: 30.6728,
      lng: 104.1085,
      address: '成都市成华区建设路53号',
      avgPrice: 95,
      rating: 4.8,
      bloggerId: 'b2',
      bloggerName: '盗月社食遇记',
      visitDate: '2025-10-21',
      recommendDishes: ['耙牛肉', '耗儿鱼', '贡菜'],
      tags: ['重庆风味', '好停车', '深夜食堂'],
      note: '盗月社说耙牛肉软烂入味，是他吃过最好吃的火锅牛肉',
    },
    {
      id: 's007',
      name: '邓记新一代糖油果子',
      category: '小吃',
      lat: 30.6562,
      lng: 104.0698,
      address: '成都市锦江区镗钯街37号',
      avgPrice: 10,
      rating: 4.3,
      bloggerId: 'b4',
      bloggerName: '肉肉大搜索',
      visitDate: '2025-09-29',
      recommendDishes: ['糖油果子', '三大炮', '蛋烘糕'],
      tags: ['街边小吃', '童年的味道', '现做现卖'],
      note: '肉肉说这是他吃过最酥脆的糖油果子，外脆里糯',
    },
    {
      id: 's008',
      name: '钦善斋·食养餐厅',
      category: '创意料理',
      lat: 30.6489,
      lng: 104.0589,
      address: '成都市武侯区科华北路143号',
      avgPrice: 180,
      rating: 4.6,
      bloggerId: 'b5',
      bloggerName: '日食记',
      visitDate: '2025-08-15',
      recommendDishes: ['药膳滋补汤', '松茸焖饭', '金汤花胶'],
      tags: ['高端餐饮', '养生药膳', '环境雅致'],
      note: '日食记拍出了一整集纪录片质感，说每一道菜都是艺术品',
    },
    {
      id: 's009',
      name: '肥肠粉大全（青石桥店）',
      category: '面馆',
      lat: 30.6552,
      lng: 104.0756,
      address: '成都市锦江区青石桥北街28号',
      avgPrice: 25,
      rating: 4.4,
      bloggerId: 'b3',
      bloggerName: '唐仁杰',
      visitDate: '2025-10-06',
      recommendDishes: ['肥肠粉', '军屯锅盔', '冒节子'],
      tags: ['三十年老店', '肥肠处理干净', '手工粉'],
      note: '唐仁杰：肥肠处理得极其干净，粉条是纯手工红薯粉',
    },
    {
      id: 's010',
      name: '何师烧烤（九眼桥店）',
      category: '烧烤',
      lat: 30.6432,
      lng: 104.0889,
      address: '成都市武侯区九眼桥太平南新街6号',
      avgPrice: 80,
      rating: 4.5,
      bloggerId: 'b1',
      bloggerName: '密子君',
      visitDate: '2025-11-17',
      recommendDishes: ['烤脑花', '烤五花肉', '锡纸金针菇'],
      tags: ['夜宵之王', '九眼桥地标', '烟火气'],
      note: '密子君一个人扫荡了整张菜单，说烤脑花是成都天花板',
    },
    {
      id: 's011',
      name: '廖记棒棒鸡（总店）',
      category: '小吃',
      lat: 30.6612,
      lng: 104.0725,
      address: '成都市青羊区提督街108号',
      avgPrice: 40,
      rating: 4.3,
      bloggerId: 'b4',
      bloggerName: '肉肉大搜索',
      visitDate: '2025-09-30',
      recommendDishes: ['棒棒鸡', '无骨凤爪', '红油兔丁'],
      tags: ['凉菜之王', '下酒神器', '可以打包'],
      note: '肉肉说红油是灵魂，廖记的红油配方几十年没变过',
    },
    {
      id: 's012',
      name: '马路边边麻辣烫（致民路店）',
      category: '火锅',
      lat: 30.6415,
      lng: 104.0782,
      address: '成都市武侯区致民路48号',
      avgPrice: 70,
      rating: 4.5,
      bloggerId: 'b6',
      bloggerName: '吃货请闭眼',
      visitDate: '2025-07-22',
      recommendDishes: ['嫩牛肉', '冒椒千层肚', '冰汤圆'],
      tags: ['复古装修', '80年代怀旧', '麻辣烫界扛把子'],
      note: '吃货请闭眼说一进门就像穿越回了80年代的成都街头',
    },
    {
      id: 's013',
      name: '蜀大侠火锅（宽窄巷子店）',
      category: '火锅',
      lat: 30.6695,
      lng: 104.0521,
      address: '成都市青羊区宽窄巷子长顺街88号',
      avgPrice: 110,
      rating: 4.6,
      bloggerId: 'b2',
      bloggerName: '盗月社食遇记',
      visitDate: '2025-10-22',
      recommendDishes: ['花千骨', '冰川鹅肠', '贵妃牛肉'],
      tags: ['武侠主题', '颜值高', '网红打卡'],
      note: '盗月社说这是成都最有仪式感的火锅，每道菜都是一个故事',
    },
    {
      id: 's014',
      name: '盘飧市（华兴街店）',
      category: '川菜',
      lat: 30.6582,
      lng: 104.0795,
      address: '成都市锦江区华兴正街62号',
      avgPrice: 90,
      rating: 4.4,
      bloggerId: 'b3',
      bloggerName: '唐仁杰',
      visitDate: '2025-10-07',
      recommendDishes: ['卤味拼盘', '锅巴肉片', '鱼香肉丝'],
      tags: ['近百年老店', '卤味成都第一', '老成都味道'],
      note: '唐仁杰：盘飧市的卤水配方传承近百年，是成都卤味的活化石',
    },
    {
      id: 's015',
      name: '甘食记成都肥肠粉（太古里店）',
      category: '面馆',
      lat: 30.6545,
      lng: 104.0842,
      address: '成都市锦江区太古里B1层',
      avgPrice: 35,
      rating: 4.2,
      bloggerId: 'b1',
      bloggerName: '密子君',
      visitDate: '2025-11-18',
      recommendDishes: ['招牌肥肠粉', '牛肉锅盔', '冰醉豆花'],
      tags: ['商场美食', '太古里', '快速用餐'],
      note: '商场里的地道肥肠粉，密子君说水准不输路边老店',
    },
    {
      id: 's016',
      name: '叶婆婆钵钵鸡（望平街店）',
      category: '小吃',
      lat: 30.6568,
      lng: 104.0882,
      address: '成都市成华区望平街119号',
      avgPrice: 45,
      rating: 4.6,
      bloggerId: 'b4',
      bloggerName: '肉肉大搜索',
      visitDate: '2025-09-27',
      recommendDishes: ['红油钵钵鸡', '藤椒钵钵鸡', '醪糟冰粉'],
      tags: ['冷锅串串', '外卖首选', '藤椒一绝'],
      note: '肉肉说叶婆婆的藤椒味是一绝，麻辣中带着清香',
    },
    {
      id: 's017',
      name: '喜茶·茶极客实验室（IFS店）',
      category: '甜品饮品',
      lat: 30.6565,
      lng: 104.0833,
      address: '成都市锦江区红星路三段1号IFS 6楼',
      avgPrice: 45,
      rating: 4.3,
      bloggerId: 'b5',
      bloggerName: '日食记',
      visitDate: '2025-08-16',
      recommendDishes: ['多肉葡萄', '芝芝莓莓', '季节限定甜品'],
      tags: ['网红饮品', '打卡圣地', '熊猫主题'],
      note: '日食记在这拍了一整集奶茶美学，画面美到每一帧都能做壁纸',
    },
    {
      id: 's018',
      name: '烤匠麻辣烤鱼（蓝色加勒比店）',
      category: '烧烤',
      lat: 30.6475,
      lng: 104.0552,
      address: '成都市武侯区科华北路143号蓝色加勒比广场2楼',
      avgPrice: 85,
      rating: 4.7,
      bloggerId: 'b6',
      bloggerName: '吃货请闭眼',
      visitDate: '2025-07-23',
      recommendDishes: ['麻辣烤鱼', '黑豆花', '芝士烤红薯'],
      tags: ['烤鱼天花板', '大学生最爱', '性价比高'],
      note: '吃货请闭眼说吃完这条鱼才知道什么叫真正的川式烤鱼',
    },
    {
      id: 's019',
      name: '叁無粉蒸（玉林店）',
      category: '川菜',
      lat: 30.6278,
      lng: 104.0535,
      address: '成都市武侯区玉林南路52号',
      avgPrice: 35,
      rating: 4.4,
      bloggerId: 'b2',
      bloggerName: '盗月社食遇记',
      visitDate: '2025-10-23',
      recommendDishes: ['粉蒸牛肉', '粉蒸肥肠', '樱桃肉'],
      tags: ['粉蒸专门店', '老成都味道', '一人食友好'],
      note: '盗月社说这是成都最纯粹的粉蒸系列，每一种都蒸出了灵魂',
    },
    {
      id: 's020',
      name: 'wagas沃歌斯（万象城店）',
      category: '轻食简餐',
      lat: 30.6512,
      lng: 104.1156,
      address: '成都市成华区双庆路8号万象城B1层',
      avgPrice: 75,
      rating: 4.1,
      bloggerId: 'b5',
      bloggerName: '日食记',
      visitDate: '2025-08-17',
      recommendDishes: ['烤鸡肉牛油果沙拉', '鲜榨果汁', '轻食碗'],
      tags: ['健康轻食', '健身餐', 'brunch'],
      note: '日食记的轻食探店系列，画面清新治愈',
    },
  ],
};

// 品类分类及图标
const CATEGORIES = [
  { key: 'all', label: '全部', icon: '🍽️' },
  { key: '火锅', label: '火锅', icon: '🫕' },
  { key: '川菜', label: '川菜', icon: '🌶️' },
  { key: '小吃', label: '小吃', icon: '🥟' },
  { key: '面馆', label: '面馆', icon: '🍜' },
  { key: '烧烤', label: '烧烤', icon: '🍖' },
  { key: '甜品饮品', label: '甜品饮品', icon: '🍰' },
  { key: '创意料理', label: '创意料理', icon: '✨' },
  { key: '轻食简餐', label: '轻食简餐', icon: '🥗' },
];

// 品类配色方案
const CATEGORY_COLORS = {
  '火锅': '#ef4444',
  '川菜': '#f97316',
  '小吃': '#eab308',
  '面馆': '#84cc16',
  '烧烤': '#ec4899',
  '甜品饮品': '#a855f7',
  '创意料理': '#06b6d4',
  '轻食简餐': '#22c55e',
};
