"""
Migrate existing SQLite data into PostgreSQL.

Usage:
    set DATABASE_URL=postgresql://postgres:password@localhost:5432/tandian
    python backend/scripts/migrate_sqlite_to_postgres.py --reset

Run this from the project root: tandian-app.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
from pathlib import Path

try:
    import psycopg
except ImportError as exc:
    raise SystemExit(
        "Missing dependency: psycopg. Install it with: pip install \"psycopg[binary]\""
    ) from exc


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SQLITE_PATH = PROJECT_ROOT / "data" / "tandian.db"

TABLES = [
    "bloggers",
    "videos",
    "stores",
    "analysis_logs",
    "analysis_steps",
    "users",
    "user_sessions",
    "user_favorites",
    "config",
]

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS bloggers (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    platform text NOT NULL DEFAULT 'bilibili',
    platform_uid text NOT NULL UNIQUE,
    avatar text DEFAULT '',
    followers text DEFAULT '',
    bio text DEFAULT '',
    status text DEFAULT 'active',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS videos (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    blogger_id integer NOT NULL REFERENCES bloggers(id) ON DELETE CASCADE,
    platform_video_id text NOT NULL,
    title text NOT NULL,
    description text DEFAULT '',
    cover_url text DEFAULT '',
    tags text DEFAULT '[]',
    publish_date text DEFAULT '',
    url text DEFAULT '',
    duration text DEFAULT '',
    play_count text DEFAULT '',
    status text DEFAULT 'new',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(blogger_id, platform_video_id)
);

CREATE TABLE IF NOT EXISTS stores (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    category text DEFAULT '',
    lat double precision DEFAULT 0,
    lng double precision DEFAULT 0,
    address text DEFAULT '',
    avg_price double precision DEFAULT 0,
    rating double precision DEFAULT 0,
    recommend_dishes text DEFAULT '[]',
    tags text DEFAULT '[]',
    note text DEFAULT '',
    source_video_id integer REFERENCES videos(id),
    source_blogger_id integer REFERENCES bloggers(id),
    confidence double precision DEFAULT 0,
    status text DEFAULT 'active',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analysis_logs (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_id integer NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    model_name text DEFAULT '',
    prompt_tokens integer DEFAULT 0,
    completion_tokens integer DEFAULT 0,
    raw_response text DEFAULT '',
    extracted_data text DEFAULT '{}',
    store_ids text DEFAULT '[]',
    success boolean DEFAULT false,
    error_message text DEFAULT '',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analysis_steps (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_id integer NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    analysis_log_id integer REFERENCES analysis_logs(id) ON DELETE SET NULL,
    run_id text DEFAULT '',
    step_name text NOT NULL,
    status text DEFAULT 'running',
    started_at timestamp DEFAULT CURRENT_TIMESTAMP,
    ended_at timestamp,
    duration_ms integer DEFAULT 0,
    input_summary text DEFAULT '',
    output_summary text DEFAULT '',
    error_message text DEFAULT '',
    metadata_json text DEFAULT '{}',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    openid text NOT NULL UNIQUE,
    unionid text DEFAULT '',
    nickname text DEFAULT '探店用户',
    avatar text DEFAULT '',
    status text DEFAULT 'active',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_sessions (
    token text PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status text DEFAULT 'active',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_favorites (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    store_id integer NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    status text DEFAULT 'active',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, store_id)
);

CREATE TABLE IF NOT EXISTS config (
    key text PRIMARY KEY,
    value text DEFAULT '',
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_videos_blogger ON videos(blogger_id);
CREATE INDEX IF NOT EXISTS idx_videos_status ON videos(status);
CREATE INDEX IF NOT EXISTS idx_stores_category ON stores(category);
CREATE INDEX IF NOT EXISTS idx_stores_status_category ON stores(status, category);
CREATE INDEX IF NOT EXISTS idx_stores_source ON stores(source_video_id);
CREATE INDEX IF NOT EXISTS idx_stores_source_blogger ON stores(source_blogger_id);
CREATE INDEX IF NOT EXISTS idx_analysis_video ON analysis_logs(video_id);
CREATE INDEX IF NOT EXISTS idx_analysis_steps_video ON analysis_steps(video_id);
CREATE INDEX IF NOT EXISTS idx_analysis_steps_log ON analysis_steps(analysis_log_id);
CREATE INDEX IF NOT EXISTS idx_analysis_steps_run ON analysis_steps(run_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_favorites_user ON user_favorites(user_id, status);
CREATE INDEX IF NOT EXISTS idx_user_favorites_store ON user_favorites(store_id, status);
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--sqlite",
        default=str(SQLITE_PATH),
        help="Path to source SQLite database.",
    )
    parser.add_argument(
        "--database-url",
        default=os.environ.get("DATABASE_URL", ""),
        help="PostgreSQL connection URL. Defaults to DATABASE_URL env var.",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Truncate target tables before importing. Use only for a fresh target database.",
    )
    return parser.parse_args()


def sqlite_tables(conn: sqlite3.Connection) -> set[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ).fetchall()
    return {row["name"] for row in rows}


def rows_from_sqlite(conn: sqlite3.Connection, table: str) -> list[dict]:
    rows = conn.execute(f"SELECT * FROM {table}").fetchall()
    return [dict(row) for row in rows]


def insert_rows(pg_conn, table: str, rows: list[dict]) -> None:
    if not rows:
        return

    columns = list(rows[0].keys())
    placeholders = ", ".join(["%s"] * len(columns))
    quoted_columns = ", ".join(f'"{col}"' for col in columns)
    query = f'INSERT INTO "{table}" ({quoted_columns}) VALUES ({placeholders}) ON CONFLICT DO NOTHING'

    values = []
    for row in rows:
        if table == "analysis_logs" and "success" in row:
            row["success"] = bool(row["success"])
        values.append(tuple(row[col] for col in columns))

    with pg_conn.cursor() as cur:
        cur.executemany(query, values)


def reset_tables(pg_conn) -> None:
    table_list = ", ".join(f'"{table}"' for table in reversed(TABLES))
    with pg_conn.cursor() as cur:
        cur.execute(f"TRUNCATE TABLE {table_list} RESTART IDENTITY CASCADE")


def sync_identity_sequences(pg_conn) -> None:
    id_tables = [table for table in TABLES if table not in ("config", "user_sessions")]
    with pg_conn.cursor() as cur:
        for table in id_tables:
            cur.execute(
                f"""
                SELECT setval(
                    pg_get_serial_sequence('{table}', 'id'),
                    COALESCE((SELECT MAX(id) FROM "{table}"), 1),
                    (SELECT MAX(id) FROM "{table}") IS NOT NULL
                )
                """
            )


def count_pg(pg_conn, table: str) -> int:
    with pg_conn.cursor() as cur:
        cur.execute(f'SELECT COUNT(*) FROM "{table}"')
        return cur.fetchone()[0]


def main() -> None:
    args = parse_args()
    if not args.database_url:
        raise SystemExit(
            "DATABASE_URL is required, for example: "
            "postgresql://postgres:password@localhost:5432/tandian"
        )

    sqlite_path = Path(args.sqlite)
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_path}")

    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row
    source_tables = sqlite_tables(sqlite_conn)

    with psycopg.connect(args.database_url) as pg_conn:
        with pg_conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)

        if args.reset:
            reset_tables(pg_conn)

        for table in TABLES:
            if table not in source_tables:
                print(f"skip {table}: source table not found")
                continue
            rows = rows_from_sqlite(sqlite_conn, table)
            insert_rows(pg_conn, table, rows)
            print(f"imported {table}: {len(rows)} rows")

        sync_identity_sequences(pg_conn)
        pg_conn.commit()

        print("\nverification:")
        for table in TABLES:
            if table not in source_tables:
                continue
            source_count = len(rows_from_sqlite(sqlite_conn, table))
            target_count = count_pg(pg_conn, table)
            marker = "OK" if source_count == target_count else "MISMATCH"
            print(f"{marker} {table}: sqlite={source_count}, postgres={target_count}")

    sqlite_conn.close()


if __name__ == "__main__":
    main()
